version: '3.1'
services:
  go-redirect:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TZ=Asia/Shanghai
      - GIN_MODE=release
    container_name: go-redirect
    volumes:
      - ./config.yml:/root/config.yml
    ports:
      - 5555:5555